#!/usr/bin/env bash

set -e

if [[ $(ls "$1" 2>/dev/null) ]]; then
  INPUT=$(cat "$1")
elif test ! -t 0; then # "stdin has data"
  INPUT=$(</dev/stdin)
elif [[ $(ls ".gitlab-ci.yml" 2>/dev/null) ]]; then
  INPUT=$(cat ".gitlab-ci.yml")
else
  echo ".gitlab-ci.yml not found"
  exit 3
fi

GITLAB_API_URL=${2:-${GITLAB_API_URL:-"https://gitlab.com/api/v4"}}
GITLAB_TOKEN=${3:-${GITLAB_TOKEN:-$CI_JOB_TOKEN}}

RESPONSE=$(
  jq --null-input --arg yaml "$INPUT" '.content=$yaml' \
   | curl -s "${GITLAB_API_URL}/ci/lint" \
      --header 'Content-Type: application/json' \
      --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
      --data @-
)

echo "$RESPONSE"

STATUS=$(echo "$RESPONSE" | jq -r '.status')

if [[ $STATUS == 'valid' ]]; then
    exit 0
elif [[ $STATUS == 'invalid' ]]; then
    exit 1
else
    exit 2
fi
