#!/usr/bin/env bash

set -e

GITLAB_CI_FILE=${1:-${GITLAB_CI_FILE:-".gitlab-ci.yml"}}
GITLAB_TOKEN=${2:-$GITLAB_TOKEN}
GITLAB_API_URL=${3:-${GITLAB_API_URL:-"https://gitlab.com/api/v4"}}

RESPONSE=$(
  jq --null-input --arg yaml "$(<"${GITLAB_CI_FILE}")" '.content=$yaml' \
   | curl -s "${GITLAB_API_URL}/ci/lint" \
      --header 'Content-Type: application/json' \
      --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
      --data @-
)

echo "$RESPONSE"

STATUS=$(echo "$RESPONSE" | jq -r '.status')

if [[ $STATUS == 'valid' ]]; then
    exit 0
elif [[ $STATUS == 'invalid' ]]; then
    exit 1
else
    exit 2
fi
